name: Snapshot Release

on:
  pull_request:
    types: [labeled]
concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  prepare:
    if: |
      (github.event.label.name == 'release: snapshot')
    name: Snapshot Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Unlabel PR
        run: |
          gh pr edit $GITHUB_HEAD_REF --remove-label='release: snapshot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  release:
    needs: [prepare]
    uses: ./.github/workflows/release.yml
    with:
      ref_name: ${{ github.head_ref }}
      release_type: 'snapshot'
    secrets: inherit
